package model;

import java.util.List;

/**
 * Represents a single job posting, either fetched live from a job-market
 * API or generated by the mock/demo data source.
 */
public class JobPosting {
    private String title;
    private String company;
    private String description;
    private List<String> skills;

    public JobPosting(String title, String company, String description, List<String> skills) {
        this.title = title;
        this.company = company;
        this.description = description;
        this.skills = skills;
    }

    public String getTitle() { return title; }
    public String getCompany() { return company; }
    public String getDescription() { return description; }
    public List<String> getSkills() { return skills; }

    @Override
    public String toString() {
        return title + " @ " + company + " -> " + skills;
    }
}
